#!/bin/bash
set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}CommandLauncher has been installed successfully!${NC}"
echo -e "${GREEN}You can now run CommandLauncher by typing 'commandlauncher' in your terminal or by searching for it in your application menu.${NC}"
echo -e "${GREEN}If you have any issues, please report them at ${BLUE}https://github.com/CesarGarza55/CommandLauncher/issues${NC}"
echo -e "${GREEN}Don't forget to check out the website at ${BLUE}https://commandlauncher.codevbox.com${NC}"
echo -e "${GREEN}Enjoy!${NC}"